### ISSUE TITLE
Error in v1.1.0 on .NET 4.6.1: System.Runtime not found in the GAC

### ISSUE THREAD

**Issue by ben-reilly** [MichaCo/DnsClient.NET#24] opened 2018-06-12 22:15 UTC
When I try to update my nuget package from v1.0.7 to v1.1.0 on .NET 4.6.1, I get the following error:

    Failed to add reference. The package 'DnsClient' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

It appears that another package, NLog, experienced the same problem, so the solution might be found here: https://github.com/NLog/NLog.Extensions.Logging/issues/91

**Comment by MichaCo** [comment] 2018-06-12 23:55
Hey @ben-reilly, thanks for letting me know.
I just double checked and I had:

```
  <ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System.Runtime" />
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
```

Since the beginning of time (of this library) in the project file.

For whatever reason, only the 1.1.0 version now has this in the nuspec:
```
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Runtime" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Xml.Serialization" targetFramework=".NETFramework4.5.1" />
    </frameworkAssemblies>
```

Which seem to cause those issues...

I can reproduce it with VS2015, VS2017 doesn't have any issues. Seems to be a nuget package manager issue...

I'll try to fix it somehow

**Comment by MichaCo** [comment] 2018-06-13 00:30
should be fixed in v1.1.1

**Closed by MichaCo** 2018-06-13 00:30 UTC

**Comment by ben-reilly** [comment] 2018-06-13 00:37
That was fast! Confirmed it works in v1.1.1; thank you!

**Comment by MichaCo** [comment] 2018-06-13 00:47
Great ;)
