### ISSUE TITLE
DnsUdpMessageHandler keeps duplicate responses in socket and reused by later queries, causes header ID mismatch

### ISSUE THREAD

**Issue by euyuil** [MichaCo/DnsClient.NET#145] opened 2022-01-30 07:48 UTC
I had similar issue with #140 and reviewed #142. I agree the approach of retry on header ID mismatch can increase the possibility of success. And I also think the implementation of [`DnsUdpMessageHandler`](https://github.com/MichaCo/DnsClient.NET/blob/d56cb12b1768afdaecbc576b492f47a501fb6c00/src/DnsClient/DnsUdpMessageHandler.cs) needs to be improved in the case we can have duplicate responses.

The class maintains two queues for UDP clients to be reused. As the code shows:

https://github.com/MichaCo/DnsClient.NET/blob/d56cb12b1768afdaecbc576b492f47a501fb6c00/src/DnsClient/DnsUdpMessageHandler.cs#L112-L130

A UDP client will be enqueued for later reuse after receiving data from it. However, based on the fact that we have duplicate responses, a UDP client can still receive data even after it has been enqueued. So it will later get reused by another query, and in that query it will read some nonsense response.

I think that is (one of) the root cause(s) why `LookupClient` got confused as described in #140. So I propose to improve the class `DnsUdpMessageHandler` to better support the duplicate response scenario.

**Comment by MichaCo** [comment] 2022-01-30 08:20
Hi @euyuil 
Thanks for taking the time to test and replicate that behavior. I hope you can help me test the changes later on, too ;)

But for this issue, I'd consider it a duplicate of ##132.
I'm already working on removing the pooling for UDP traffic as mentioned in that issue. (almost done)

**Closed** 2022-01-30 19:38 UTC
