### ISSUE TITLE
NameServer  timed out

### ISSUE THREAD

**Issue by m4wayne** [MichaCo/DnsClient.NET#185] opened 2023-03-02 03:23 UTC
Hi @MichaCo
I tested using DnsClient.NET and DNS respectively. DnsClient.NET threw an exception and DNS got the correct result.The brand of network equipment is DLink.

exception:
引发的异常:“DnsClient.DnsResponseException”(位于 mscorlib.dll 中)
Query 2998 => www.bing.com IN AAAA on 192.168.0.1:53 timed out or is a transient error.

![image](https://user-images.githubusercontent.com/6783828/222322092-4b87d87e-e185-4e66-a0e7-9f37114cb2b3.png)

**Comment by MichaCo** [comment] 2023-03-04 15:09
Its a timeout error, nothing I can do here. Might be your network or something else being slowish.
/closing because cannot be reproduced

**Closed by MichaCo** 2023-03-04 15:09 UTC
