### ISSUE TITLE
Additionals count varies for the same MX lookup

### ISSUE THREAD

**Issue by DASCert** [MichaCo/DnsClient.NET#39] opened 2018-12-16 01:11 UTC
Hi Michael
Thanks for creating this client.  It has saved me a lot of time.
I have an issue where I'm doing an MX lookup for a domain and the Client returns the three expected records in the Answers but the Additionals count varies.  Most of the time it returns the Additionals for Answer(0) only (whichever record happens to be there)  but every once in a while it will return the Additionals for two of the answers (not necessarily Answer(0) and Answer(1)) and very rarely the Additionals for all three Answers.  If I Dig the domain, I get all 38 records.  Have I missed some setting?

**Comment by MichaCo** [comment] 2019-06-22 07:52
Hi,
Closing this because of lack of information to reproduce and probably had nothing to do with this library.

**Closed by MichaCo** 2019-06-22 07:52 UTC

**Comment by DASCert** [comment] 2019-06-23 06:01
Hi Michael
If you had asked for further information, I would have been happy to supply the code I had used.

Since the code in question does nothing much except call your library, I regret having to confirm that it does have something to do with your library.  

In the absence of a response, I found another library that doesn't have this fault so it now works correctly.  

Thanks anyway.

**Comment by MichaCo** [comment] 2019-06-23 08:01
@DASCert, why don't you just post the code to reproduce it??

The code isn't that important actually, it is more about the DNS server(s) used and the actual query you run so that I can reproduce it...

I'm guessing here, but if you get different results if you call it a couple of times, that's usually because you use multiple DNS servers and those can return different things. Per default, DnsClient alternates the DNS Servers, but you can also a) configure only one, b) configure the Lookup Client to always use the configured servers in order.

**Comment by DASCert** [comment] 2019-06-25 01:50
Hi Michael

The code is really simple.

    Sub Main()
        Dim DNSClient As New LookupClient
        Dim MX_Records As IDnsQueryResponse
        Dim ThisDomain As String

        ThisDomain = "google.com"

        MX_Records = DNSClient.Query(ThisDomain, QueryType.MX)


    End Sub

If I DIG google.com mx I get
![image](https://user-images.githubusercontent.com/37386893/60062063-fe308200-973a-11e9-9602-fa141bcf3311.png)

When I run the code the first time and inspect the returned variable I get
![image](https://user-images.githubusercontent.com/37386893/60062133-3df76980-973b-11e9-88cb-55abee5bbebe.png)
Note 9 additionals where dig gives me 10

On a subsequent run of the code, I get 6 additionals
![image](https://user-images.githubusercontent.com/37386893/60062169-62ebdc80-973b-11e9-86e5-1bc336dbdeb7.png)

Run it again and I get a different 6
![image](https://user-images.githubusercontent.com/37386893/60062189-7b5bf700-973b-11e9-96ad-31a022274942.png)

Re-run the dig command and I get the additionals in a different order but I get them all
![image](https://user-images.githubusercontent.com/37386893/60062273-e0175180-973b-11e9-8eda-a3695393b5da.png)

Am I doing something wrong?  Is it a timeout issue?  Am I using the library incorrectly?

**Comment by MichaCo** [comment] 2019-06-25 08:29
Thanks @DASCert for taking the time to send some more details.
I don't really 100% know what this is and I still cannot reproduce it though.
But those results solely on the response it is getting from the DNS server(s).
I don't know what DNS server you are using, meaning I will probably get very different results then you.

You seem to not configure any servers which means the library will try to use whatever is configured in your network. DIG might use a different server. Any of those servers might be configured as forwarders and use other DNS Servers to resolve the query and then there is caching, too.

For example, I don't get any additionals from public DNS servers (8.8.8.8) for the `google.com mx` query.
This is normal because most public DNS servers do not return/resolve recursive queries and in most cases don't send any additionals back.

I tested this a bit with running BIND locally as a resolver/cache server and I'm 100% getting the same response all the time for `google.com mx`  with (in my case) 18 additionals.

**Comment by DASCert** [comment] 2019-06-25 08:53
Hi @MichaCo 
There is just one DNS server involved - the Microsoft DNS server on the local domain controller and DIG is using the same DNS.  To simplify testing, I have set it to have one forwarder, 8.8.8.8

I don't see an option to *set* the nameserver to be used.  How do I do it?

**Comment by MichaCo** [comment] 2019-06-25 09:24
You can pass in servers in the constructor of LookupClient.
